# Generated by Django 5.0.6 on 2024-12-11 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_hired_on_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='days_employed',
        ),
    ]
