# Generated by Django 5.0.6 on 2024-12-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_days_employed'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hired_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
