# Generated by Django 5.0.6 on 2024-12-11 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_email_employee_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
            preserve_default=False,
        ),
    ]
