# Generated by Django 5.0.6 on 2024-12-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnBoardingApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('Application Received', 'Application Received'), ('Interview Scheduled', 'Interview Scheduled'), ('Hired', 'Hired'), ('Not Accepted', 'Not Accepted')], default='Application Received', max_length=20)),
            ],
            options={
                'verbose_name': 'Onboarding Applicant',
                'verbose_name_plural': 'Onboarding Applicants',
                'ordering': ['-id'],
            },
        ),
    ]
