# Generated by Django 5.0.6 on 2024-12-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_company_name_company_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='num_of_departments',
        ),
        migrations.RemoveField(
            model_name='company',
            name='num_of_employess',
        ),
    ]
