# Generated by Django 5.0.6 on 2024-12-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_company_num_of_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
