# Generated by Django 5.0.6 on 2024-12-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='dept_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='num_of_employees',
        ),
    ]
