# Generated by Django 5.0.6 on 2024-12-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_rename_name_department_dept_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
